# Header
menu:
  Home: /
  About: /about
  Contact: /contact

# Favicon
favicon_url: https://pic.guanjigj.green/resample/favicon-x64-6fa78041154889a627b87a6f4f8716ed466b8937a4c6e04e79f8c2541403e76b.webp

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: mailto:welcome@guanjigj.green
twitter_url: https://x.com/guanji58720
facebook_url:
instagram_url:
linkedin_url:
dribbble_url:
github_url:
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname: