# Header
menu:
  Home: /
  About: /about
  Contact: /contact

# Favicon
favicon_url: https://alist.asen.page/d/189cloud/static/guanjigj.green/resample/favicon-x64-f3e5948a1422c4dc6059fcb625c16d3fa75fdc7f3eb20dc39892d3b543c15c70.webp

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: mailto:welcome@guanjigj.green
twitter_url: https://x.com/guanji58720
facebook_url:
instagram_url:
linkedin_url:
dribbble_url:
github_url:
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname: guanji